### ISSUE TITLE
How to change server

### ISSUE THREAD

**Issue by gitsheikhgit** [bolemo/pia_wg#10]
Thank you for this script, it worked as expected. If I want to change server from New York to toronto, how can I do it? Do I need to run the script again and select the server or there is any  short cut?

**Comment by bolemo** [comment]
Hello @gitsheikhgit. Thank you for your interest and feedback.

Just run this command:
`pia_wg.sh configure region`
Then follow the instructions to pick your region, here Toronto, then run this command:
`pia_wg.sh restart`

**Comment by gitsheikhgit** [comment]
Thanks

**Comment by gitsheikhgit** [comment]
Thanks it worked. Maybe if you can do an implementation of selecting 5-6 servers of choice when selecting servers during initial running the script and that will create 5-6 peers in the configuration. This way it will be easier to just enable or disable servers from Luci instead of running the script from cmd.
