### ISSUE TITLE
PIA wg interface stops forwarding traffic after a few weeks

### ISSUE THREAD

**Issue by bwitt** [bolemo/pia_wg#11]
After a few weeks or so of running the wg pia connection, the wg interface will still be up and connected, but no longer responding:

```
# wg
interface: wg_pia
  public key: <pubkey>
  private key: (hidden)
  listening port: 37724

peer: <peer>
  endpoint: <peer IP>
  allowed ips: ::/0, 0.0.0.0/0
  latest handshake: 7 hours, 9 minutes, 36 seconds ago
  transfer: 222.89 GiB received, 66.59 GiB sent
  persistent keepalive: every 25 seconds
```

and when I try `pia_wg.sh start` (e.g. as in the watchdog cron) I get:
```
# ./pia_wg.sh start
WireGuard PIA interface: UP
Region is: <PIA region>
Connectivity through PIA: NOK
User is configured
Local keys are configured
Network interface options are configured
Network peer options are configured
PIA region is configured
Renewing PIA token
Error fetching PIA token!
```

**Comment by bwitt** [comment]
note along with https://github.com/bolemo/pia_wg/pull/12 I also had to follow https://openwrt.org/docs/guide-user/services/vpn/wireguard/extras#dynamic_connection to ensure the default route for my wan interface is preserved when the wg interface comes up.

**Comment by bolemo** [comment]
Thanks @bwitt :)
I would not have caught this as I am not sending all my traffic through the VPN, but only selected marked packets.
