### ISSUE TITLE
created wg interface not in wan zone

### ISSUE THREAD

**Issue by bwitt** [bolemo/pia_wg#3]
When I ran this and it created the wg interface, it didn't put the new interface into the 'wan' zone.  I had to do that manually.  Does this make sense to do in the script and can we do that automatically?

**Comment by bolemo** [comment]
Hello @bwitt,
First, thank you for your contribution; My OpenWrt installation has a lot of package, so I missed to define the dependencies that are not _standard_.

Regarding the firewall zone, I prefer not to put it in the script as not everybody set up their zones the same way. For exemple, my VPN in not the WAN zone, but on its own separate zone.

However, I will think of adding a comment in the ReadMe to remind people to adapt their firewall zones to take the vpn into account.

**Comment by bwitt** [comment]
sure, a note in the README would work too!
