### ISSUE TITLE
Script reports "Connectivity through PIA: OK" even when no traffic can be sent

### ISSUE THREAD

**Issue by bwitt** [bolemo/pia_wg#6]
I noticed if the other side of the wg tunnel stops responding, but the link stays up, the script will still report:
```
Connectivity through PIA: OK
```

This particular case happens to me periodically, where the remote side stops responding somehow but the link is up.  The Latest Handshake is old too.

**Comment by bolemo** [comment]
Thank you @bwitt, good catch :)
